logging:
  level:
    org.springframework: error
    org.mybatis: debug
    io.gitee: debug
spring:
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/Message
  datasource:
    url: jdbc:mysql://192.168.99.110/fly-feel
    username: fly-feel
    password: fly-feel2022!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  jackson:
    default-property-inclusion: non_null
  freemarker:
    suffix: .html
  mvc:
    throw-exception-if-no-handler-found: true
mybatis:
  mapper-locations:
    - classpath*:mapper/**/*Mapper.xml
server:
  port: 8080
