
logging:
  level:
    #    org.springframework: error
    org.mybatis: debug
    io.gitee: debug
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  jackson:
    default-property-inclusion: non_null
  freemarker:
    suffix: .html
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: Cikaros
          client-secret: 123456
          introspection-uri: http://localhost:8080/oauth/check_token
server:
  port: 8081
