logging:
  level:
    io.gitee: debug
spring:
  messages:
    basename: i18n/Message
  freemarker:
    suffix: .html
  mvc:
    throw-exception-if-no-handler-found: true
feign:
  paths:
    demo: http://localhost:9090
  client:
    config:
      default:
        loggerLevel: FULL
server:
  port: 9090